language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: PK8ong3toRnzLcTjZjo03wlf0Oeg9HWW5sGqOEvaKUu7CUdoV1TYyhA3zyQN4EQeWXK7rA5hdrnV0QLQEflouo+aUgtWPISBE5XUyLTW0eWC0dx9riMatZRzNZQw9GHAhXTeVRBnmyjW5C+Lle9WC8J/9MEA/vROc14RV3Timdo=
  - secure: BSIISg/IfU34S/YjHlE67lSFbI94pIzU0STza0FQ8dRkdtzjd/pIbnEIXeWr01uKRjU3VxxknsNWBWjbL7PgqrKLy+cC3xckbqmF/Zp9xpBjZynJlAiyN8VouRP4eT8Ftx3J7rYWuD2KNl//5EFiFiqdPWagxtEDCGxjdzlzUoU=
